#ifndef _DEFS__H
#define _DEFS__H

const int SCREEN_WIDTH = 1100;
const int SCREEN_HEIGHT = 630;

#define WINDOW_TITLE "Chess"
#define BOARD_X 350
#define BOARD_Y 115
#define CELL_SIZE 50
#define PROMOTED_WHITE_BOARD_X 350
#define PROMOTED_WHITE_BOARD_Y 50
#define PROMOTED_BLACK_BOARD_X 650
#define PROMOTED_BLACK_BOARD_Y 533
#define PROMOTED_BOARD_WIDTH 212
#define PROMOTED_BOARD_HEIGHT 47
#define BOARD_SIZE 8
#define EMPTY_CELL ' '
#define PROMOTED_CELL_SIZE 47
#define WIN_X 183
#define WIN_Y 105
#define WIN_WIDTH 700
#define WIN_HEIGHT 400


#endif